anguage: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
  sonarcloud:
    organization: "jamro-github"
before_install:
  # Enable user namespace cloning
  - "sudo sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
node_js:
  - 8
install:
  - npm install
script:
  - npm run-script ci
  - sonar-scanner -Dsonar.verbose=true -X
