version: 2.1
orbs:
  node: circleci/node@4.7.0

parameters:
  app-id:
    type: string
    default: "jsbattle"

jobs:
  build:
    docker:
      - image: 'circleci/node'
    steps:
      - checkout
      - run:
          name: Install Graphviz
          command: sudo apt install -y graphviz
      - run:
          name: Install Java
          command: | 
            sudo apt install -y default-jdk
            java --version
      - run: 
          name: Install Libs
          command: |
            sudo apt install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
            sudo apt install -y libgbm-dev 
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Bootstrap Project
          command: npm run bootstrap
      - run:
          name: Clean Project
          command: npm run clean
      - run:
          name: Lint Project
          command: npm run lint
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Test Project
          command: npm run test

workflows:
  cicd-workflow:
    jobs:
      - build