---
# tasks file for jsbattle
  - name: Install git
    yum:
      name: git

  - name: Clean app path
    file:
      state: absent
      path: "{{ jsbattle_dest }}/jsbattle"

  - name: Get JsBattle from GitHub
    git:
      repo: https://github.com/jamro/jsbattle.git
      dest: "{{ jsbattle_dest }}/jsbattle"
      version: "{{ jsbattle_version }}"

  - name: Install dependencies
    command: npm install --unsafe-perm=true --allow-root
    args:
      chdir: "{{ jsbattle_dest }}/jsbattle"

  - name: Stop APP
    shell: pm2 stop jsbattle || true

  - name: Delete APP
    shell: pm2 del jsbattle || true

  - name: Start APP
    shell: pm2 start {{ jsbattle_dest }}/jsbattle/dist/jsbattle.js -- start -h {{ jsbattle_address }} -p {{ jsbattle_port }}
