---
# tasks file for nginx_forward
  - name: Configure Nginx forward
    template:
      src: module.conf
      dest: "/etc/nginx/conf.d/{{ nginx_forward_name }}.conf"

  - name: Restart Nginx
    systemd:
      state: restarted
      daemon_reload: yes
      name: nginx
